services:
  app-prod:
    image: bolt-ai:production
    build:
      context: .
      dockerfile: Dockerfile
      target: bolt-ai-production
    ports:
      - '5173:5173'
    env_file:
      - '.env.production'
      - '.env.local'
    environment:
      - NODE_ENV=production
      - COMPOSE_PROFILES=production
      # No strictly needed but serving as hints for Coolify
      - PORT=5173
      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL:-debug}
      - DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX:-32768}
      - RUNNING_IN_DOCKER=true
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command: pnpm run dockerstart
    profiles:
      - production
      - production-tls

  nginx:
    image: nginx:alpine
    depends_on:
      - app-prod
    ports:
      - '80:80'
    volumes:
      - ./nginx/templates/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-web:/var/www/certbot
    restart: unless-stopped
    environment:
      - SERVER_NAME=mojocode.sixtyoneeighty.com
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
    profiles:
      - production

  # TLS-enabled nginx. Use after certificates are issued.
  nginx-tls:
    image: nginx:alpine
    depends_on:
      - app-prod
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/templates/default.ssl.conf.template:/etc/nginx/templates/default.conf.template:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-web:/var/www/certbot
    restart: unless-stopped
    environment:
      - SERVER_NAME=mojocode.sixtyoneeighty.com
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
    profiles:
      - production-tls

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-web:/var/www/certbot
    entrypoint: |
      sh -c 'trap exit TERM; while :; do sleep 12h & wait $$!; certbot renew --webroot -w /var/www/certbot --quiet; done'
    profiles:
      - production
      - production-tls

  # One-shot cert issuance using your SERVER_NAME
  certbot-init:
    image: certbot/certbot:latest
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-web:/var/www/certbot
    environment:
      - SERVER_NAME=mojocode.sixtyoneeighty.com
      - LETSENCRYPT_EMAIL=admin@mojocode.sixtyoneeighty.com
    entrypoint: >
      sh -c 'certbot certonly --webroot -w /var/www/certbot -d "$SERVER_NAME" --email "$LETSENCRYPT_EMAIL" --agree-tos --no-eff-email'
    profiles:
      - production-init

  app-dev:
    image: bolt-ai:development
    build:
      target: bolt-ai-development
    env_file: 
      - '.env'
      - '.env.local'
    environment:
      - NODE_ENV=development
      - VITE_HMR_PROTOCOL=ws
      - VITE_HMR_HOST=localhost
      - VITE_HMR_PORT=5173
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - PORT=5173
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL:-debug}
      - DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX:-32768}
      - RUNNING_IN_DOCKER=true
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - type: bind
        source: .
        target: /app
        consistency: cached
      - /app/node_modules
    ports:
      - '5173:5173'
    command: pnpm run dev --host 0.0.0.0
    profiles: ['development', 'default']

  app-prebuild:
    image: ghcr.io/stackblitz-labs/bolt.diy:latest
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=production
      - COMPOSE_PROFILES=production
      # No strictly needed but serving as hints for Coolify
      - PORT=5173
      - OLLAMA_API_BASE_URL=http://127.0.0.1:11434
      - DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX:-32768}
      - RUNNING_IN_DOCKER=true
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command: pnpm run dockerstart
    profiles:
      - prebuilt

volumes:
  certbot-etc:
  certbot-var:
  certbot-web:
